[package]
name = "lxd-snapper"
version = "1.1.0"
license = "MIT"
authors = ["Patryk Wychowaniec <pwychowaniec@pm.me>"]
edition = "2021"

[workspace]
members = [
    "libs/*",
]

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "3.0.0-beta.5"
colored = "2.0"
indexmap = { version = "1.7", features = ["serde-1"] }
prettytable-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

lib_lxd = { path = "libs/lxd" }

[dev-dependencies]
glob = "0.3"
indoc = "1.0"
pretty_assertions = "1.0"
