[package]
name = "lxd-snapper"
version = "1.0.0"
license = "MIT"
authors = ["Patryk Wychowaniec <wychowaniec.patryk@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "libs/*",
]

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = "3.0.0-beta.2"
colored = "1.8"
indexmap = { version = "1.4", features = ["serde-1"] }
prettytable-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

lib_lxd = { path = "libs/lxd" }

[dev-dependencies]
glob = "0.3"
indoc = "0.3"
pretty_assertions = "0.6"
