[package]
name = "lxd-snapper"
version = "0.1.0"
license = "MIT"
authors = ["Patryk Wychowaniec <wychowaniec.patryk@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "src/lib_command",
    "src/lib_config",
    "src/lib_driver",
    "src/lib_lxd",
]

[dependencies]
lib_driver = { path = "src/lib_driver" }
