#!/usr/bin/env bash

set -e

echo 'Testing'
./test

echo
echo 'Building'

echo '- i686-linux'
nix build .#defaultPackage.i686-linux
cp ./result/bin/lxd-snapper lxd-snapper-linux32
rm result

echo '- x86_64-linux'
nix build .#defaultPackage.x86_64-linux
cp ./result/bin/lxd-snapper lxd-snapper-linux64
rm result

echo
echo 'Done'
